services:
  web:
    container_name: php
    userns: keep-id
    user: "${UID}:${GID}"
    build:
      context: app_php
      target: builder
    volumes:
      - ../src:/var/www/html:Z
    ports:
      - '8080:8080'
    depends_on:
        - mysql
  mysql:
    container_name: mysql
    user: "${UID}:${GID}"
    image: docker.io/mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tp
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql:Z
  phpmyadmin:
      image: docker.io/phpmyadmin/phpmyadmin:5.2.1
      platform: linux/amd64
      container_name: phpmyadmin
      environment:
        PMA_HOST: mysql
        PMA_USER: user
        PMA_PASSWORD: pass
        UPLOAD_LIMIT: 20M
      ports:
        - 8082:80
      depends_on:
        - mysql
